name: Release Workflow

on:
  workflow_dispatch:
     inputs:
      version:
        type: string
        description: Version number
        required: true
      

jobs:
  call-workflow:
    permissions: 
      contents: write

    uses: crystal-nest/.github/.github/workflows/version_update.yml@main
    with:
      version: ${{ github.event.inputs.version }}
    secrets: inherit
    
    uses: crystal-nest/.github/.github/workflows/single_release.yml@main
    with:
      loader_forge: true
      loader_fabric: true
      loader_neoforge: true
      loader_common: true
      platform_maven: true
      platform_github: true
      platform_curseforge: true
      platform_modrinth: true
    secrets: inherit
