name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version number
        required: true
      enable_version_checks:
        type: boolean
        description: Enable version consistency checks
        default: true  # Checkbox is checked by default

jobs:
  call-analyze-workflow:
    uses: crystal-nest/.github/.github/workflows/analyze.yml@main
    secrets: inherit 
  call-version-update-workflow:
    needs: call-analyze-workflow
    permissions: 
      contents: write
    uses: crystal-nest/.github/.github/workflows/version_update.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      disable_checks: ${{ not github.event.inputs.enable_version_checks }}
    secrets: inherit
  call-release-workflow:
    needs: [call-analyze-workflow, call-version-update-workflow]
    permissions: 
      contents: write
      packages: write
    uses: crystal-nest/.github/.github/workflows/release.yml@main
    secrets: inherit

