name: Release Workflow

on:
  workflow_call:

jobs:
  release:
    permissions: 
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pull
      run: git pull --no-rebase
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'microsoft'
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Set permission
      run: chmod +x ./gradlew
    - name: Build
      run: |
        ./gradlew wrapper
        ./gradlew build 
    - name: Set Command Release
      run: |
        ./gradlew publishAll --stacktrace
          
          
