name: Remove Labels From Closed Items
on:
  workflow_call:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          remove-labels: "highest priority, high priority, medium priority, low priority, no priority, pending"
