name: Single Release Workflow

on:
  workflow_call:
    inputs:
      loader_forge:
        type: string
        description: Forge Loader
        default: false
      loader_fabric:
        type: string
        description: Fabric Loader
        default: false
      loader_neoforge:
        type: string
        description: NeoForge Loader
        default: false
      loader_common:
        type: string
        description: Common Loader
        default: false
      platform_maven:
        type: string
        description: Publish to Maven
        default: false
      platform_github:
        type: string
        description: Publish to GitHub
        default: false
      platform_curseforge:
        type: string
        description: Publish to CurseForge
        default: false
      platform_modrinth:
        type: string
        description: Publish to Modrinth
        default: false

jobs:
  single_release:
    permissions: 
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Pull
      run: git pull --no-rebase
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Set permission
      run: chmod +x ./gradlew
    - name: Build
      run: |
        ./gradlew wrapper
        ./gradlew build 
    - name: Set Command
      run: |
          loaders=()
          if [ "${{ inputs.loader_forge }}" == "true" ]; then
            loaders+=("forge")
          fi
          if [ "${{ inputs.loader_fabric }}" == "true" ]; then
            loaders+=("fabric")
          fi
          if [ "${{ inputs.loader_neoforge }}" == "true" ]; then
            loaders+=("neoforge")
          fi
          if [ "${{ inputs.loader_common }}" == "true" ]; then
            loaders+=("common")
          fi
          for loader in "${loaders[@]}"; do
            if [ "${{ inputs.platform_maven }}" == "true" ]; then
              ./gradlew ${loader}:publish --stacktrace
            fi
            if [ "${{ inputs.platform_github }}" == "true" ]; then
              ./gradlew ${loader}:publishGitHub --stacktrace
            fi
            if [ "${{ inputs.platform_curseforge }}" == "true" ]; then
              ./gradlew ${loader}:publishCurseforge --stacktrace
            fi
            if [ "${{ inputs.platform_modrinth }}" == "true" ]; then
              ./gradlew ${loader}:publishModrinth --stacktrace
            fi
          done
