name: Version Update
on:
  workflow_call:  
    inputs:
      version:
        type: string
        description: Version number
        required: true

jobs:
  version_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            gradle.properties
          sparse-checkout-cone-mode: false
      - name: Check if version has changed
        id: check_version
        run: |
          version_input="${{ github.event.inputs.version }}"
          current_version=$(grep -oP '^mod_version = \K.*' gradle.properties)
          echo "Current version: $current_version"
          echo "Input version: $version_input"
          if [ "$version_input" = "$current_version" ]; then
            echo "Version is already up to date."
            echo "outcome=no_changes" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Versions are different."
            echo "outcome=version_change" >> $GITHUB_OUTPUT
          fi
      - name: Update gradle.properties
        if: steps.check_version.outputs.outcome == 'version_change'
        run: |
          version_input="${{ github.event.inputs.version }}"
          sed -i "s/^mod_version = .*/mod_version = $version_input/" gradle.properties
      - name: Commit and push changes
        if: steps.check_version.outputs.outcome == 'version_change'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add gradle.properties
          git commit -m "Update mod_version to ${{ github.event.inputs.version }}"
          git push
