name: Version Update
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: Version number
        required: true

jobs:
  version_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check if version has changed
      id: check_version
      run: |
        version_input="${{ github.event.inputs.version }}"
        current_version=$(grep -oP '^mod_version = \K.*' gradle.properties)
        if [ "$version_input" = "$current_version" ]; then
          echo "Version is the same. Exiting gracefully."
          exit 0
        fi
    - name: Update gradle.properties
      if: steps.check_version.outcome == 'success'  # Only execute if version has changed
      run: |
        version_input="${{ github.event.inputs.version }}"
        sed -i "s/^mod_version = .*/mod_version = $version_input/" gradle.properties
    - name: Commit and push changes
      if: steps.check_version.outcome == 'success'  # Only execute if version has changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add gradle.properties
        git commit -m "Update mod_version to ${{ github.event.inputs.version }}"
        git push
